### ISSUE TITLE
Pardus-store açılmıyor

### ISSUE THREAD

**Issue by vlknkc** [yunusem/pardus-store#21]
Mağazayı çalıştırdığımda hemen kapanıyor. Terminal üzerinden çalıştırdığımda aşağıdaki hatayı alıyorum. Githubdaki son güncellemeyi indirdim fakat nasıl derleneceğini bulamadım
Hata çıktısı şöyle

```

    vlkn@pardus:~$ sudo pardus-store 

    [sudo] password for vlkn:
    qrc:/ui/Home.qml:637:17: QML Image: Failed to get image from provider: image://application/
    Parçalama arızası

```

**Comment by gokhanettin** [comment]
`apt list pardus-store` yapıp hangi versiyonu kullandığına bakabilir misin? Ben Pardus 17.3'ü yeni yükledim pardus store `0.2.0~beta5` yüklü geldi. Dediğin hatayı oluşturamadım.

Kendin build etmek istiyorsan [control](https://github.com/yunusem/pardus-store/blob/master/debian/control) dosyasında gerekli bağımlılıklar var. Önce onları indirmen gerekiyor.
```
apt-get install
    libc6  \
   libgcc1 \
    libgcc-6-dev \
    libgl1-mesa-glx \
    libqt5core5a \
    libqt5gui5 \
    libqt5network5 \
    libqt5qml5 \
    libqt5quick5 \
    libqt5svg5-dev \
    libqt5widgets5 \
    libstdc++6 \
    qtdeclarative5-dev
```
Build etmek için
```
cd pardus-store
mkdir build
qmake ..
make
sudo ./pardus-store # Test test
make install # Tamamsa yükle
```

**Comment by gokhanettin** [comment]
@yunusem @vlknkc Ben de kendim build edince benzer hatayı aldım ama her şey normal çalışıyor. Bende seg fault olmadığından program kapanmıyor.

```
sudo ./pardus-store 
qrc:/ui/Home.qml:637:17: QML Image: Failed to get image from provider: image://application/
```
