### ISSUE TITLE
Yazılım tanıtım metni sığmıyor

### ISSUE THREAD

**Issue by oktay454** [yunusem/pardus-store#23]
Selamün Aleyküm
Resimde görüldüğü gibi yazılım tanıtım metni, ekrana sığmamış. Eğer metin; mevcut ekran çözünürlüğündeki metin için ayrılmış alana sığmıyorsa ilgili alanın sağına, kaydırma çubuğu eklenecek şekilde düzenleme yapılabilirse çok iyi olur.

![ekran goruntusu_2018-09-06_15-05-41](https://user-images.githubusercontent.com/1449620/45160880-34743380-b1f3-11e8-98e3-6cbfdbe17a19.png)

**Comment by yunusem** [comment]
Fixed after [0.2.1_beta4](https://github.com/yunusem/pardus-store/releases/tag/debian%2F0.2.1_beta4)
