### ISSUE TITLE
Uygulama açıklamalarına web siteleri eklenmesi

### ISSUE THREAD

**Issue by ilteriskeskin** [yunusem/pardus-store#25]
Merhaba **/src/applicationdetail.h** üzerinde web sitesi eklenmesi ile ilgili bir çalışma yaptım ancak başarılı olmadığı için commit atmadım. Forumda dile getirmiştim bu konuyu, uygulama detay bölümünde o uygulamanın web sitesi görünürse çok güzel olur. Şimdiden teşekkür ederim.

**Comment by yunusem** [comment]
https://github.com/yunusem/pardus-store/blob/master/ui/ApplicationDetail.qml

You should look on this one.

**Comment by yunusem** [comment]
It is fixed in new releases. Above [0.2.1](https://github.com/yunusem/pardus-store/releases/tag/debian%2F0.2.1_beta4)
