### ISSUE TITLE
Deb paketini indirme seçeneği

### ISSUE THREAD

**Issue by mahmutelmas06** [yunusem/pardus-store#27]
Kurma dışında bir de deb paketini indirme seçeneği güzel olur.
İndire tıklayınca tüm bağımlılıklarıyla beraber paketi bir klasöre indirsek. İnternet olmayan ortamlar için

**Comment by gokhanettin** [comment]
İnterneti olmayan ortamlar (air gap) için en ideal çözüm bence local mirror yapmak [Sonatype Nexus](https://www.sonatype.com/nexus-repository-sonatype) ve [Artifactory](https://jfrog.com/artifactory/) bu işi daha kolay hale getirebilir. Local mirror yapıldıktan sonra da pardus-store da ihtiyaç duyulacak özellik repository adresini değiştirebilmek olacaktır.

Ayrıca [AppImage](https://appimage.github.io/) adında bir paketleme yöntemi daha var. Air gap network için eğer ihtiyaç sadece uygulama indirmekse çok kullanışlı olabilir.` yourapp.appimage`  dosyasını internetten indiriyorsunuz çalıştırılabilir yapıyorsunuz ve hiç bir bağımlılık sorunuyla uğraştırmadan çalışıyor.

**Comment by yunusem** [comment]
Therefore, its is not related with pardus-store' s install mechanism. Irrelevant.
