### ISSUE TITLE
Sürücüleri mağazadan yükleme

### ISSUE THREAD

**Issue by mahmutelmas06** [yunusem/pardus-store#31]
Biliyorsunuz ki linuxda özellikle Ekran kartı sürücüleri yükleme büyük problem. Mağazaya Sürücüler sekmesi açıp ekran kartı başta  olmak üzere sürücüleri yükleme kolaylığı sağlamak olmazsa olmaz. Bunun dışında zamanla mağaza geliştikçe diğer tak kullan cihazların sürücüleri de bu bölümde yer alabilir. Örneğin akıllı telefonlara ait sürücüler, tak kullan wifi adaptörleri, oyun kontrol cihazları, akıllı tahtalara ait sürücüler vs...

**Comment by yunusem** [comment]
Unfortunately, this is not related of this projects' purposes.
