### ISSUE TITLE
İşlem kuyruğu

### ISSUE THREAD

**Issue by alitelli** [yunusem/pardus-store#34]
İşlem kuyruğu görülebilmeli uygulamalar üzerinde gözüküyor fakat liste şeklinde kuyruktaki işlemlerin listelendiği bir kısım olmalı

**Comment by yunusem** [comment]
Resolved with [this commit](https://github.com/yunusem/pardus-store/commit/2ed8d30538b7d88be130037f38a21d8ff82244cd)

**Comment by alitelli** [comment]
now we can see the queue of the process but there is one process can't cancel which is in downloading step.

**Comment by yunusem** [comment]
Yes you can cancel while downloading but after that step  "installing" you cant. That is the design we cannot change.
