### ISSUE TITLE
Mağazayı paket yöneticisi olarak kullanma

### ISSUE THREAD

**Issue by mahmutelmas06** [yunusem/pardus-store#39]
Uygulamalar gdebi gerektirmeden mağaza üzerinden de kurulabilir olabilir. Bir deb, flatpack dosyasına çift tıkladigimizda magazada ilgili uygulama varsa onun detay sayfasını acip yüklemesi, yoksa doğrudan paketi mağaza arayüzünde yuklemeye başlaması güzel olurdu. Ubuntu magazada olduğu gibi.

**Comment by yunusem** [comment]
I think it is irrelevant with the main goal of the application. In ubuntu they call it **software center** but we call it store.
