### ISSUE TITLE
Uygulamalar arası gezerken son bakılan ekrana geri dönmek

### ISSUE THREAD

**Issue by mahmutelmas06** [yunusem/pardus-store#41]
Forumdan alıntıdır.

> Herhangi bir uygulamanın detaylarına bakmak için uygulamaya tıklıyorum detaylarına baktıktan sonra geri düğmesine bastığımda son kaldığım yerden uygulamalara bakmaya devam edilse daha hoş 

olur.

**Comment by yunusem** [comment]
It already has this feature.
