### ISSUE TITLE
Uygulama metadata'ları için AppStream kullanmak

### ISSUE THREAD

**Issue by payonpowbl** [yunusem/pardus-store#43]
Uygulamaları eklemek, güncellemek ve bilgi eklemek gibi işleri el ile halletmek yerine evrensel AppStream metadata'sı kullanılabilir: https://www.freedesktop.org/wiki/Distributions/AppStream/

Diğer tüm major dağıtımların yaptığı gibi.

**Comment by yunusem** [comment]
Bunu farketmediğimizi düşünmeniz, yada bilmediğimizi farzetmeniz çok üzücü. Appstream ın devasa eksikleri olduğu için ve gereken interaktiviteyi sağlayamadığı için tercih edilmemiştir.

**Comment by veyselerden** [comment]
Alınacak bir şey değildi neden duygusal bir cevap geldi anlayamadım. Var olan uygulamaların sürümleri nispeten çok eski buradan cıkarım yaptım.
